# Generated by Django 5.2 on 2025-09-17 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_type', models.CharField(max_length=16)),
                ('target', models.CharField(max_length=512)),
                ('interval_seconds', models.PositiveIntegerField(default=30)),
                ('timeout_seconds', models.PositiveIntegerField(default=5)),
                ('enabled', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('os', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('result', models.CharField(max_length=8)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitoring.probe')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('hostname', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('status', models.CharField(default='UNKNOWN', max_length=16)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='monitoring.server')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='monitoring.servicetype')),
            ],
        ),
        migrations.AddField(
            model_name='probe',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='monitoring.service'),
        ),
    ]
