# Generated by Django 5.2 on 2025-10-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16),
        ),
    ]
