# Generated by Django 5.2 on 2025-10-29 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='monitoring.server'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='monitoring.servicetype'),
        ),
    ]
