# Generated by Django 5.2 on 2025-10-01 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_app', '0001_initial'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logevent',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_source', to='logging_app.logsource'),
        ),
        migrations.AlterField(
            model_name='logsource',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitoring.service'),
        ),
    ]
