# Generated by Django 5.2 on 2025-10-01 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_app', '0002_alter_logevent_source_alter_logsource_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logevent',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='logging_app.logsource'),
        ),
    ]
